dbAccessSynchronous  = false
testText = "これはてすとなの！！"
dbFileName = 'chatroom.db'
useJson = false
lcchatCuiCommand = 'Sqltest.exe'


[hotkeys]
# toggleVisible = 'CommandOrControl+Shift+A'
toggleVisible = 'CommandOrControl+Shift+Z'
