dbAccessSynchronous  = false
dbFilePath = '${appPath}/chatroom.db'
# dbFilePath = 'C:\Users\shimp\Desktop\chatroom.db'
# lcchatCuiCommand = 'C:\Users\shimp\OneDrive\Documents\lcchat\bin\cpp\Sqltest.exe'
# lcchatCuiCommand = '${appPath}/../lcchat/bin/cpp/Sqltest.exe'
## lcchatCuiCommand = 'C:\Users\shimp\OneDrive\Documents\lcchat\nim\sqltest.exe'
# lcchatCuiCommand = '${appPath}\..\lcchat\nim\sqltest.exe'
# lcchatCuiCommand = 'neko "${appPath}/../lcchat/Sqltest.n"'
lcchatCuiCommand = '"${appPath}/Sqltest.exe"'


[hotkeys]
# toggleVisible = 'CommandOrControl+Shift+A'
toggleVisible = 'CommandOrControl+Shift+Z'
