dbAccessSynchronous  = false
# dbFilePath = '${appPath}/chatroom.db'
dbFilePath = '${appPath}/../lcchat/db/chatroom.db'
# lcchatCuiCommand = '"${appPath}/Sqltest.exe"'
lcchatCuiCommand = '"${appPath}/../lcchat/lcchat.exe"'


[hotkeys]
# toggleVisible = 'CommandOrControl+Shift+A'
toggleVisible = 'CommandOrControl+Shift+Z'
