dbAccessSynchronous  = false
dbFileName = 'aaa.db'
useJson = false
# lcchatCuiCommand = '{$appPath}\Sqltest.exe'
lcchatCuiCommand = 'neko {$appPath}\Sqltest.n'


[hotkeys]
# toggleVisible = 'CommandOrControl+Shift+A'
toggleVisible = 'CommandOrControl+Shift+Z'
