dbAccessSynchronous  = false
dbFileName = 'aaa.db'
useJson = false
# lcchatCuiCommand = 'C:\Users\shimp\OneDrive\Documents\lcchat\bin\cpp\Sqltest.exe'
lcchatCuiCommand = 'C:\Users\shimp\OneDrive\Documents\lcchat\nim\sqltest.exe'
# lcchatCuiCommand = '${appPath}/../lcchat/bin/cpp/Sqltest.exe'
# lcchatCuiCommand = '"${appPath}/Sqltest.exe"'
# lcchatCuiCommand = 'neko "${appPath}/Sqltest.n"'


[hotkeys]
# toggleVisible = 'CommandOrControl+Shift+A'
toggleVisible = 'CommandOrControl+Shift+Z'
